### ISSUE TITLE
Want to show pdf with URL is possible

### ISSUE THREAD

**Issue by saravananNV** [Marxon13/M13PDFKit#23]
hi,

  I want to show the pdf from a web url and i dont want to save it locally on the app or phone.is it possible using this library.if possible.can anyone please help me with it. i tried a  lot.

Thanks

**Comment by simalexan** [comment]
Hello @saravananNV,
First, opening any type of file from a web url - requires the app to virtually "download" the content in order to display it. (That's how browsers do it - the data is just hidden)

With that in mind, if you do not want to permanently save the PDF on the user phone (meaning that is just temporarily used) - `<Application_Home>/Library/Caches` is where you would store your it just for this single usage, as per [Apple Data Storage guidelines](https://developer.apple.com/icloud/documentation/data-storage/index.html)

Currently in the library there is no option of downloading directly from a url, but we may put it as a possibility (though we would implement it like it was previously mentioned) 

if you have any further questions, feel free to ask

**Comment by saravananNV** [comment]
hi,

so there is no option to view the pdf file from http uri using this library,only way to download it on cache and view it using this library

and how to work with PDFKBasicPDFViewerThumbsCollectionView.what is the use of it
